//! Translates Mandelbulber2's OpenCL fractal formulas into WGSL fragments for
//! 3DM's formula stack.
//!
//!     cargo run -p mb2-transpile -- <mandelbulber2-checkout> [--report-only]
//!
//! Mandelbulber2 is GPL-3.0, which is why 3DM is too. See the project README.

mod translate;
mod types;
mod validate;

use std::collections::BTreeMap;
use std::path::Path;

use translate::Rejected;
use types::TypeMap;

fn main() {
    let mut args = std::env::args().skip(1);
    let root = args.next().unwrap_or_else(|| {
        eprintln!("usage: mb2-transpile <mandelbulber2-checkout> [--report-only]");
        std::process::exit(2);
    });
    let rest: Vec<String> = args.collect();
    let report_only = rest.iter().any(|a| a == "--report-only");
    let show_errors = rest.iter().any(|a| a == "--errors");

    let root = Path::new(&root);
    let header = root.join("mandelbulber2/opencl/fractal_cl.h");
    let formula_dir = root.join("mandelbulber2/formula/opencl");

    let header_src = std::fs::read_to_string(&header)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", header.display()));
    let type_map = TypeMap::parse(&header_src);

    let mut files: Vec<_> = std::fs::read_dir(&formula_dir)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", formula_dir.display()))
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|x| x == "cl"))
        .collect();
    files.sort();

    let mut ok = Vec::new();
    let mut rejected: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut samples: Vec<String> = Vec::new();

    for path in &files {
        let name = path.file_name().unwrap().to_string_lossy().to_string();
        let src = match std::fs::read_to_string(path) {
            Ok(s) => s,
            Err(e) => {
                rejected
                    .entry(format!("unreadable: {e}"))
                    .or_default()
                    .push(name);
                continue;
            }
        };

        match translate::translate(&name, &src, &type_map) {
            // Translating is not the same as compiling: only formulas naga
            // accepts are counted, so the report reflects shippable coverage.
            Ok(f) => match validate::check(&f) {
                Ok(()) => ok.push(f),
                Err(e) => {
                    if show_errors && samples.len() < 12 {
                        samples.push(format!("{name}: {e}"));
                    }
                    rejected.entry(classify(&e)).or_default().push(name)
                }
            },
            Err(Rejected::Unsupported(why)) | Err(Rejected::Malformed(why)) => {
                rejected.entry(why.to_owned()).or_default().push(name);
            }
        }
    }

    let total = files.len();
    println!("Mandelbulber2 -> WGSL coverage");
    println!("  translated : {} / {total}", ok.len());
    println!(
        "  rejected   : {} / {total}",
        total.saturating_sub(ok.len())
    );
    println!("\nrejections by cause:");
    let mut causes: Vec<_> = rejected.iter().collect();
    causes.sort_by_key(|(_, v)| std::cmp::Reverse(v.len()));
    for (why, which) in causes {
        println!("  {:>4}  {why}", which.len());
    }

    if !ok.is_empty() {
        let params: Vec<usize> = ok.iter().map(|f| f.param_floats).collect();
        let max = params.iter().copied().max().unwrap_or(0);
        let mean = params.iter().sum::<usize>() as f32 / params.len() as f32;
        println!("\nparameter block (f32 slots): mean {mean:.1}, max {max}");
    }

    if show_errors {
        println!("\nsample errors:");
        for s in &samples {
            println!("  {s}");
        }
    }

    if report_only {
        return;
    }

    let out = Path::new("src/formulas/generated.wgsl.rs");
    if let Some(dir) = out.parent() {
        std::fs::create_dir_all(dir).ok();
    }
    std::fs::write(out, emit(&ok)).unwrap_or_else(|e| panic!("cannot write {}: {e}", out.display()));
    println!("\nwrote {} formulas to {}", ok.len(), out.display());
}

/// Emits the generated formula table as Rust.
/// Groups naga errors so the report shows what to fix next rather than 300
/// individually-worded messages.
fn classify(err: &str) -> String {
    for (needle, label) in [
        ("no definition in scope", "wgsl: undefined name"),
        ("expected", "wgsl: parse error"),
        ("type", "wgsl: type mismatch"),
        ("must be", "wgsl: type mismatch"),
        ("cannot", "wgsl: invalid operation"),
    ] {
        if err.contains(needle) {
            return label.to_owned();
        }
    }
    "wgsl: other".to_owned()
}

fn emit(formulas: &[translate::Formula]) -> String {
    let mut s = String::new();
    s.push_str(
        "//! GENERATED by `tools/mb2-transpile` — do not edit.\n\
         //!\n\
         //! Translated from Mandelbulber2's OpenCL formula sources\n\
         //! (<https://github.com/buddhi1980/mandelbulber2>, © Mandelbulber Team,\n\
         //! GPL-3.0). 3DM is GPL-3.0-or-later as a result.\n\n\
         use super::{GeneratedFormula, GeneratedParam, ParamKind};\n\n\
         pub static GENERATED: &[GeneratedFormula] = &[\n",
    );

    for f in formulas {
        s.push_str(&format!(
            "    GeneratedFormula {{\n        name: {:?},\n        source: {:?},\n        param_floats: {},\n        params: &[\n",
            f.name, f.source_file, f.param_floats
        ));
        for p in &f.params {
            s.push_str(&format!(
                "            GeneratedParam {{ path: {:?}, kind: ParamKind::{:?}, offset: {} }},\n",
                p.path, p.ty, p.offset
            ));
        }
        s.push_str("        ],\n        wgsl: r####\"");
        s.push_str(&f.wgsl_body);
        s.push_str("\"####,\n    },\n");
    }

    s.push_str("];\n");
    s
}
